In [1]:
import numpy as np
A=np.array([[2,4],[3,5]])
B=np.array([[6,4],[7,1]])
print(np.matmul(A,B))

print(A+B)

print(A/B)


[[40 12]
 [53 17]]
[[ 8  8]
 [10  6]]
[[0.33333333 1.        ]
 [0.42857143 5.        ]]


In [2]:
# transpose

import numpy as np
A=np.array([[1,2,4],[6,3,5]])
print(A.T)

[[1 6]
 [2 3]
 [4 5]]


In [3]:
# identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Inverse matrix 
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [5]:
# determinant of matrix
a=np.array([[1,2],[3,4]])
print(np.linalg.det(a))

-2.0000000000000004


In [6]:
import numpy as np

# Matrix A
A = np.array([
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18]
])

# Matrix B
B = np.array([
    [1, 3, 5],
    [7, 9, 11],
    [13, 15, 17]
])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix B:
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [14]:
# Q1
print(A.shape)
print(A.size)
print(A.ndim)
print(B.shape)
print(B.size)
print(B.ndim)


(3, 3)
9
2
(3, 3)
9
2


In [15]:
# Q2
print(A+B)


[[ 3  7 11]
 [15 19 23]
 [27 31 35]]


In [16]:
# Q3
print(A-B)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
# Q4
print(A*B)

[[  2  12  30]
 [ 56  90 132]
 [182 240 306]]


In [18]:
# Q5
print(np.matmul(A,B))

[[108 132 156]
 [234 294 354]
 [360 456 552]]


In [19]:
# Q6
print(A.T)
print(B.T)

[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]


In [22]:
# Q7
print(np.linalg.det(A))

5.329070518200782e-15


In [23]:
# Q8
print(np.linalg.inv(A))

[[-2.25179981e+15  4.50359963e+15 -2.25179981e+15]
 [ 4.50359963e+15 -9.00719925e+15  4.50359963e+15]
 [-2.25179981e+15  4.50359963e+15 -2.25179981e+15]]


In [25]:
# Q9
print(np.trace(A))
print(np.trace(B))

30
27


In [28]:
# Q 10
print(np.max(A))
print(np.min(A))
print(np.mean(A))
print(np.sum(A))

18
2
10.0
90


In [30]:
# Q11
print(np.sum(B,axis=1))
print(np.sum(B,axis=0))

[ 9 27 45]
[21 27 33]


In [32]:
# Q12
print(A[0])
print(A[:,1])
print(A[-1])
print(A[-1,-1])

[2 4 6]
[ 4 10 16]
[14 16 18]
18


In [36]:
# Q13
print(A.reshape(1,9))
print(B.flatten())

[[ 2  4  6  8 10 12 14 16 18]]
[ 1  3  5  7  9 11 13 15 17]


In [41]:
# Q14
eigenvalues,eigenvectors=np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[ 3.22336879e+01 -2.23368794e+00 -6.95640983e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [44]:
# Q15
print(np.hstack((A,B)))
print(np.vstack((A,B)))

[[ 2  4  6  1  3  5]
 [ 8 10 12  7  9 11]
 [14 16 18 13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
