In [17]:
import numpy as np
arr= np.array([4,6,8,9])
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(arr)
print(arr1)                          #array attributes: (ndim, shape, size, dtype)
print(arr1[1,0])
print(arr2)
print(arr.ndim)
print(arr1.ndim)
print(arr.size)
print(arr1.size)
print(arr2.size)
print(arr.shape)
print(arr1.shape)

print(arr2.shape)
print(arr.dtype)
print(arr1.dtype)

print(arr[0])
print(arr[1:3:1])








[4 6 8 9]
[[1 2 3]
 [4 5 6]]
4
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
1
2
4
6
12
(4,)
(2, 3)
(2, 2, 3)
int64
int64
4
[6 8]


In [29]:
arr = np.array([1,2,3,2,0], dtype= bool)

if np.array_equal(arr , arr[::-1]):
    print("Palindrome")
else:
    print("not palindrome")



not palindrome


In [32]:
myarr=np.zeros([2,3])
print(myarr)
myarr1=np.ones((2,3))
print(myarr1)
myarr2=np.arange(1,10,2)
print(myarr2)
print(np.eye(3))


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
#aggregate function: sum,min,max,dtype

arr=[2,5,7,8,9]
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.dtype)
print("Average:", np.mean(arr))





31
2
9
<class 'numpy.dtype'>
Average: 6.2


In [54]:
arr=[5,4,3,2,6,1]
print(np.sqrt(arr))
print(np.square(arr))
print(np.abs(arr))
print(np.exp(arr))
print(np.log(arr))

[2.23606798 2.         1.73205081 1.41421356 2.44948974 1.        ]
[25 16  9  4 36  1]
[5 4 3 2 6 1]
[148.4131591   54.59815003  20.08553692   7.3890561  403.42879349
   2.71828183]
[1.60943791 1.38629436 1.09861229 0.69314718 1.79175947 0.        ]


In [1]:
 pip install pandas

Note: you may need to restart the kernel to use updated packages.
