In [1]:
import numpy as np

# Student Marks Dataset (out of 100)
marks = np.array([45, 67, 89, 90, 56, 78, 88, 92, 61, 74,
                  83, 95, 52, 68, 71, 85, 77, 64, 58, 81])

print("Dataset:")
print(marks)

Dataset:
[45 67 89 90 56 78 88 92 61 74 83 95 52 68 71 85 77 64 58 81]


In [4]:
print( np.mean(marks))

73.7


In [5]:
np.median(marks)

np.float64(75.5)

In [29]:
# 3. Mode
values, counts = np.unique(marks, return_counts=True)
max_count = np.max(counts)

if max_count == 1:
    print("3. Mode: No mode (all values occur once)")
else:
    mode = values[counts == max_count]
    print("3. Mode:", mode)

3. Mode: No mode (all values occur once)


In [7]:
np.max(marks)

np.int64(95)

In [13]:
np.min(marks)

np.int64(45)

In [12]:
np.max(marks)-np.min(marks)

np.int64(50)

In [16]:
np.var(marks)

np.float64(199.21)

In [17]:
np.std(marks)

np.float64(14.114177269681715)

In [20]:
np.percentile(marks,25)

np.float64(63.25)

In [21]:
np.percentile(marks,50)

np.float64(75.5)

In [22]:
np.percentile(marks,75)

np.float64(85.75)

In [23]:
# 11. Interquartile Range (IQR)
Q1 = np.percentile(marks, 25)
Q3 = np.percentile(marks, 75)
print("11. IQR:", Q3 - Q1)

11. IQR: 22.5


In [25]:
# 12. Students scoring above the mean
mean = np.mean(marks)
print( np.sum(marks > mean))

11


In [26]:
# 13. Students scoring below 60
print(np.sum(marks < 60))


4


In [27]:
# 14. Sum and Manual Average
total = np.sum(marks)
average = total / len(marks)
print(total)
print(average)

1474
73.7


In [28]:
# 15. Sorting and Top 5 Scores
ascending = np.sort(marks)
descending = np.sort(marks)[::-1]

print(ascending)
print(descending)
print(descending[:5])

[45 52 56 58 61 64 67 68 71 74 77 78 81 83 85 88 89 90 92 95]
[95 92 90 89 88 85 83 81 78 77 74 71 68 67 64 61 58 56 52 45]
[95 92 90 89 88]
